### ISSUE TITLE
Minimum sliding window size?

### ISSUE THREAD

**Issue by MikeEHMatson** [freemao/Genotype-corrector#5]
Hello,
It seems like the minimum window size I am allowed is 15.  Setting it to anything smaller (even 14) produces this error:

```
Traceback (most recent call last):
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 704, in <module>
    output_for_check(I, C, O)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 596, in output_for_check
    corrected_ls, orig_ls, first_line, loci_ls = main(mapfile,configfile)[0:4]
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 43, in main
    gt_onon,gt_miss,error_zeze,error_zeon,error_onon,po_type,ctg)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 72, in do_correct
    gt_onon,gt_miss,win_size,error_zeze,error_zeon,error_onon,po_type)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 99, in get_corrected_seq
    error_zeze,error_zeon, error_onon, po_type)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 231, in get_HTseq_Mseqlist
    if main_seq_ls[0] == gt_miss:
IndexError: list index out of range

```

Typically, the script will successfully process about half of the individuals before producing the error and aborting.  I want to use a smaller window size because it is correcting what I think are real recombination events which are only represented by ~5-8 markers at the end of a contig.

Any idea what might be wrong?

Thank you,
Michael

**Comment by freemao** [comment]
Hi Michael,

Just saw your message, this method only support the odd window sizes, like 11, 13, 15, 17...
But using 14 shouldn’t cause any error, I will check the code today and find the problem ASAP.

Thank you for trying this method.

Best,

Chenyong.


On Dec 4, 2017, at 17:20, MikeEHMatson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
It seems like the minimum window size I am allowed is 15. Setting it to anything smaller (even 14) produces this error:

Traceback (most recent call last):
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 704, in <module>
    output_for_check(I, C, O)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 596, in output_for_check
    corrected_ls, orig_ls, first_line, loci_ls = main(mapfile,configfile)[0:4]
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 43, in main
    gt_onon,gt_miss,error_zeze,error_zeon,error_onon,po_type,ctg)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 72, in do_correct
    gt_onon,gt_miss,win_size,error_zeze,error_zeon,error_onon,po_type)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 99, in get_corrected_seq
    error_zeze,error_zeon, error_onon, po_type)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 231, in get_HTseq_Mseqlist
    if main_seq_ls[0] == gt_miss:
IndexError: list index out of range



Typically, the script will successfully process about half of the individuals before producing the error and aborting. I want to use a smaller window size because it is correcting what I think are real recombination events which are only represented by ~5-8 markers at the end of a contig.

Any idea what might be wrong?

Thank you,
Michael

**Comment by freemao** [comment]
Hi Michael,

I just tried the window size 9, which didn’t cause any error. Did you try the smaller odd numbers? By the way, this method really depend on nearby markers. So for the SNPs at the beginning or the end, Genotype cannot process them well.
Sorry about that.

Chenyong


On Dec 4, 2017, at 17:20, MikeEHMatson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
It seems like the minimum window size I am allowed is 15. Setting it to anything smaller (even 14) produces this error:

Traceback (most recent call last):
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 704, in <module>
    output_for_check(I, C, O)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 596, in output_for_check
    corrected_ls, orig_ls, first_line, loci_ls = main(mapfile,configfile)[0:4]
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 43, in main
    gt_onon,gt_miss,error_zeze,error_zeon,error_onon,po_type,ctg)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 72, in do_correct
    gt_onon,gt_miss,win_size,error_zeze,error_zeon,error_onon,po_type)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 99, in get_corrected_seq
    error_zeze,error_zeon, error_onon, po_type)
  File "/bigdata/judelsonlab/mmatson/projects/refSeqs/genotypeCorrector_Beagle/genotypeCorrector/scripts/Genotype-corrector.py", line 231, in get_HTseq_Mseqlist
    if main_seq_ls[0] == gt_miss:
IndexError: list index out of range



Typically, the script will successfully process about half of the individuals before producing the error and aborting. I want to use a smaller window size because it is correcting what I think are real recombination events which are only represented by ~5-8 markers at the end of a contig.

Any idea what might be wrong?

Thank you,
Michael

**Comment by MikeEHMatson** [comment]
Hi Chenyong,
Yes, trying a window size of 5, 7, or 9 did actually work, apologies for not trying that sooner.  

Another thing I might suggest is to maybe introduce a feature in the binning step which can keep a subset of markers instead of consolidating every marker in a long run of identical markers.  For example, an option of keeping an identical marker every 1/4 of a way through could turn the binned marker:

“contig1-25000(40)”

to something like:

“contig1-25000(1:40”
“contig1-27000(10:40)”
"contig1-40000(20:40)”
“contig1-55000(30:40”
"contig1-75000(40:40)”

My thinking is that you are better able to keep track of how these binned markers are distributed over the interval, especially when you are comparing markers from different haplotype phases.  Just a thought.

Thanks for the help anyway!
Michael

**Comment by freemao** [comment]
That’s a good suggestion! Will do it.

Thank you!

Chenyong

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by qgao2** [comment]
Hello Chenyong, 
what's the unit for window size? the number of  SNP markers? 
Thanks!

**Comment by freemao** [comment]
Yes. The window size should be an odd number.
